### ISSUE TITLE
BT Action / Service Nodes

### ISSUE THREAD

**Issue by SteveMacenski** [BehaviorTree/BehaviorTree.ROS#3]
Hi,

Mhm, some of this looks very familiar :-)

Would you recommend any changes you made in these nodes to use back up in Nav2? Also, would you recommend that we just use this implementation of the Action / Service nodes rather than keeping a separate copy in our repos?

Steve

**Comment by facontidavide** [comment]
This repository is my personal answer to the many, many people that asked me "how do I use BT.CPP in ROS"?

Of course, I took some inspiration from Navigation2 (80%?), but you will notice that I also gave it my "personal touch" ;) 

We may eventually "merge" our efforts, but I didn't want to create too much pressure on both sides.
