### ISSUE TITLE
Visualization for ROS implementation of Behavior Tree CPP V3..?

### ISSUE THREAD

**Issue by koyalbhartia** [BehaviorTree/BehaviorTree.ROS#8]
Is there any easy and user friendly visualization of Behavior Tress available that I can implement into my code..??
I am using behaviortree_cpp_v3 and ROS Noetic. I tried using Groot, however I get a lot of ZMQ related issues. 
Request any possible help at the earliest.

**Comment by facontidavide** [comment]
Please provide a simple example to reproduce the issue you mentioned, otherwise I can not understand what is the problem you are experiencing with Groot

**Comment by koyalbhartia** [comment]
I run the following steps to get started with Groot:

sudo apt install qtbase5-dev libqt5svg5-dev libzmq3-dev libdw-dev
git clone https://github.com/BehaviorTree/Groot.git
cd Groot
git submodule update — init — recursive
mkdir build; cd build
cmake ..
make

During the "make", I face the following issue:
![Screenshot from 2021-02-25 10-29-35](https://user-images.githubusercontent.com/40532456/109184403-95da4500-7754-11eb-8587-2c22210158fe.png)

**Comment by facontidavide** [comment]
on which operative system are you truing to compile

**Comment by koyalbhartia** [comment]
Ubuntu 20.04, ROS Noetic

**Comment by facontidavide** [comment]
since you are using ROS, you should NOT us `git submodule update` .
Just compile it in a catkin workspace as any ROS package

**Comment by facontidavide** [comment]
mkdir -p catkin_ws/src
       cd catkin_ws/src
       git clone https://github.com/BehaviorTree/Groot.git
       cd ..
       rosdep install --from-paths src --ignore-src
       catkin_make

**Comment by koyalbhartia** [comment]
I wasn't able to compile on my PC, but the catkin make is working on another GPU machine with your above steps. Thanks :)
I plan to look into what's different between the 2 PCs, and put it here, so that others with a similar issue could make use of.

Now that it's compiling, is there any available documentation or steps using which I can follow to make use of Groot with my project. Thanks for your help.
